### ISSUE TITLE
网友潮易大帝

### ISSUE THREAD

**Issue by yxb1987** [chengdepolice/clue#10]
潮易大帝劝你赶紧自首吧，你知道冒充警方的后果多严重吗？

**Comment by yxb1987** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cryptoneedle** [comment]
看正起兴，咋close了家人们
