### ISSUE TITLE
这个很明显不是官方的github，大家散了吧，请理性看待这个事情！

### ISSUE THREAD

**Issue by Belen-Luo** [chengdepolice/clue#109]
先说几个现象，他为什么不是官方：
1. 官方一向言论都比较谨慎，更不用说github算是面向国际的。所以正常思维来看待，官方是不可能通过github来进行办案。
2. 其次这个文案很明显是来挑事的，所以我怀疑这个应该是间谍。
3. 如果是官方为什么不敢公布成员。
![image](https://github.com/chengdepolice/clue/assets/32587004/26c8d5ea-e870-4d9f-9b2b-3bce7fd8ce8d)

大家散了，请理性看待问题，github是一个技术平台，请不要参与这一类事件。

**Comment by xmexg** [comment]
有没有一种可能，仓库创建者是某位大佬小号，创建目的正是玩梗与讨论相关话题。

**Comment by sakaiIzumu** [comment]
有没有一种可能大家都知道不是官方

**Comment by reonce** [comment]
蒙股侠出现了

**Comment by erhulee** [comment]
感谢你，老实人

**Comment by zw531129** [comment]
蒙古人，谢谢你

**Comment by qiuxun** [comment]
我谢谢你  让我知道了不是真的官方

**Comment by Passing-of-A-Dream** [comment]
谢谢，你真是个好人，差点被蒙蔽

**Comment by silence-language** [comment]
谢谢，你真是个好人，差点被蒙蔽

**Comment by zhangfangbiao** [comment]
谢谢你，蒙古人

**Comment by Belen-Luo** [comment]
都没必要吧！！！！！！

**Comment by Belen-Luo** [comment]
这是github，请让它干净一点！

**Comment by silence-language** [comment]
> 这是github，请让它干净一点！

蒙古人，请恕我直言，你的智商玩github就是对github最大的抹黑和侮辱。

**Comment by Mr-SnowSakura** [comment]
谢谢你蒙古人，不过大火都是跑过来玩一玩

**Comment by Belen-Luo** [comment]
说真的，人生攻击的人 挺没劲的。

**Comment by Duyalun** [comment]
单纯看个乐子

**Comment by Belen-Luo** [comment]
> > 这是github，请让它干净一点！
> 
> 蒙古人，请恕我直言，你的智商玩github就是对github最大的抹黑和侮辱。

你是个什么垃圾》

**Comment by silence-language** [comment]
张嘴闭嘴就是“挑事”“间谍”，一幅苦大仇深的阶级斗争嘴脸，不是傻逼是什么？

**Comment by Belen-Luo** [comment]
你的戾气真的挺重的。

**Comment by ybkun** [comment]
> > > 这是github，请让它干净一点！
> > 
> > 
> > 蒙古人，请恕我直言，你的智商玩github就是对github最大的抹黑和侮辱。
> 
> 你是个什么垃圾》

理中客这就急了吗

**Comment by Belen-Luo** [comment]
> > > > 这是github，请让它干净一点！
> > > 
> > > 
> > > 蒙古人，请恕我直言，你的智商玩github就是对github最大的抹黑和侮辱。
> > 
> > 
> > 你是个什么垃圾》
> 
> 理中客这就急了吗

意思是只能你们喷？

**Comment by xintianyou** [comment]
谢谢

**Comment by MeiYongAI** [comment]
謝謝你，老實人😃

**Comment by DexYang** [comment]
楼主去看看脑子吧

**Comment by XINGXINGLX** [comment]
谢谢你楼主，差点让境外势力给洗脑了😀

**Comment by fernandoxu** [comment]
太忠诚了，逛g站都不忘抓50w
