### ISSUE TITLE
确定是承德公安局？

### ISSUE THREAD

**Issue by zhongqingshen** [chengdepolice/clue#180]

**Comment by lyxxxh** [comment]
能问出这样的问题 你也是牛批

**Comment by papothh76129** [comment]
见 #109 楼，https://github.com/chengdepolice/clue/issues/109

**Comment by liuguangjun** [comment]
是。想自首请留下你的姓名、联系方式、地址，请依法上缴违法所得，今晚跨省上门走访，坦白从宽抗拒从严。

**Comment by zhongqingshen** [comment]
> 能问出这样的问题 你也是牛批



> 能问出这样的问题 你也是牛批
