### ISSUE TITLE
看到一个灵魂拷问突然绷不住了

### ISSUE THREAD

**Issue by yige-yigeren** [chengdepolice/clue#348]
![image](https://github.com/chengdepolice/clue/assets/53390868/bdad749e-674f-4808-9ac7-325ef41cac6c)

**Comment by papothh76129** [comment]
pandownload事件

**Comment by A-Pupils-form-china** [comment]
C是什么事件？

**Comment by papothh76129** [comment]
https://v2ex.com/t/978379  

Minecraft正版验证api域名遭反诈中心屏蔽。 部分地区(主要是中国移动)访问api.minecraftservices.com与api.mojang.com将被301重定向至反诈中心页面  

![IMG_20231001_133638_023.jpg](https://github.com/chengdepolice/clue/assets/120825245/1e720122-25a3-4ea5-b82e-6ccb438c6e64)

![IMG_20231001_133638_391.jpg](https://github.com/chengdepolice/clue/assets/120825245/627daf33-a504-4383-9fba-b779ffc5fb64)

![IMG_20231001_133638_230.jpg](https://github.com/chengdepolice/clue/assets/120825245/f4df381a-1fa2-4fbd-8633-ec6e0fdea41d)

![IMG_20231001_133638_132.jpg](https://github.com/chengdepolice/clue/assets/120825245/7124fe78-98c7-457c-a747-d806a6bcba56)

**Comment by papothh76129** [comment]
![851.jpg](https://github.com/chengdepolice/clue/assets/120825245/9950a22b-bf89-4973-8fc7-7b2b6eb4e2f0)

![684.jpg](https://github.com/chengdepolice/clue/assets/120825245/cc826b04-7ba7-4a16-8968-01d4ab9aedd2)

![478.jpg](https://github.com/chengdepolice/clue/assets/120825245/ec803fc7-21d8-4bab-ba09-59c9ec018151)
