### ISSUE TITLE
我玩原神判几年

### ISSUE THREAD

**Issue by Tim-Saijun** [chengdepolice/clue#356]
求助，我玩原神两年半，听说判刑挺重的，在线等，我要不要自首，以及有没有经验丰富的律师能帮我减刑，价格好商量。

**Comment by papothh76129** [comment]
![IMG_20231001_134846_228.jpg](https://github.com/chengdepolice/clue/assets/120825245/2ebaa2eb-4d2b-4e2d-b6e4-3a7840b482ea)

![IMG_20231001_134846_363.jpg](https://github.com/chengdepolice/clue/assets/120825245/c9261aa5-bb0d-4fd2-8c96-299edb514b9b)

**Comment by youkniw** [comment]
.....6.这都能翻到

**Comment by papothh76129** [comment]
https://twitter.com/XOTxRixLFcXGxSi  
![大纪原.jpg](https://github.com/chengdepolice/clue/assets/120825245/9c6c9dab-62ae-434c-828d-e1b66cbb8707)

**Comment by yige-yigeren** [comment]
玩两年半那就判一坤年吧（无慈悲）
